package com.telefonica.plataformaconcursos.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.telefonica.plataformaconcursos.model.Asignados;
import com.telefonica.plataformaconcursos.service.AsignadosLocalServiceUtil;

/**
 * The extended model base implementation for the Asignados service. Represents a row in the &quot;asignados&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AsignadosImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AsignadosImpl
 * @see com.telefonica.plataformaconcursos.model.Asignados
 * @generated
 */
public abstract class AsignadosBaseImpl extends AsignadosModelImpl
    implements Asignados {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a asignados model instance should use the {@link Asignados} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AsignadosLocalServiceUtil.addAsignados(this);
        } else {
            AsignadosLocalServiceUtil.updateAsignados(this);
        }
    }
}
