package com.telefonica.plataformaconcursos.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.telefonica.plataformaconcursos.model.Empresa;
import com.telefonica.plataformaconcursos.service.EmpresaLocalServiceUtil;

/**
 * The extended model base implementation for the Empresa service. Represents a row in the &quot;empresa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmpresaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmpresaImpl
 * @see com.telefonica.plataformaconcursos.model.Empresa
 * @generated
 */
public abstract class EmpresaBaseImpl extends EmpresaModelImpl
    implements Empresa {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a empresa model instance should use the {@link Empresa} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EmpresaLocalServiceUtil.addEmpresa(this);
        } else {
            EmpresaLocalServiceUtil.updateEmpresa(this);
        }
    }
}
