package com.telefonica.plataformaconcursos.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Asignados service. Represents a row in the &quot;asignados&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.telefonica.plataformaconcursos.model.impl.AsignadosModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.telefonica.plataformaconcursos.model.impl.AsignadosImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Asignados
 * @see com.telefonica.plataformaconcursos.model.impl.AsignadosImpl
 * @see com.telefonica.plataformaconcursos.model.impl.AsignadosModelImpl
 * @generated
 */
public interface AsignadosModel extends BaseModel<Asignados>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a asignados model instance should use the {@link Asignados} interface instead.
     */

    /**
     * Returns the primary key of this asignados.
     *
     * @return the primary key of this asignados
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this asignados.
     *
     * @param primaryKey the primary key of this asignados
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the asignados ID of this asignados.
     *
     * @return the asignados ID of this asignados
     */
    @AutoEscape
    public String getAsignadosId();

    /**
     * Sets the asignados ID of this asignados.
     *
     * @param asignadosId the asignados ID of this asignados
     */
    public void setAsignadosId(String asignadosId);

    /**
     * Returns the group ID of this asignados.
     *
     * @return the group ID of this asignados
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this asignados.
     *
     * @param groupId the group ID of this asignados
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this asignados.
     *
     * @return the company ID of this asignados
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this asignados.
     *
     * @param companyId the company ID of this asignados
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this asignados.
     *
     * @return the user ID of this asignados
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this asignados.
     *
     * @param userId the user ID of this asignados
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this asignados.
     *
     * @return the user uuid of this asignados
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this asignados.
     *
     * @param userUuid the user uuid of this asignados
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this asignados.
     *
     * @return the user name of this asignados
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this asignados.
     *
     * @param userName the user name of this asignados
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this asignados.
     *
     * @return the create date of this asignados
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this asignados.
     *
     * @param createDate the create date of this asignados
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this asignados.
     *
     * @return the modified date of this asignados
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this asignados.
     *
     * @param modifiedDate the modified date of this asignados
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the usuario ID of this asignados.
     *
     * @return the usuario ID of this asignados
     */
    public long getUsuarioId();

    /**
     * Sets the usuario ID of this asignados.
     *
     * @param usuarioId the usuario ID of this asignados
     */
    public void setUsuarioId(long usuarioId);

    /**
     * Returns the concurso ID of this asignados.
     *
     * @return the concurso ID of this asignados
     */
    public long getConcursoId();

    /**
     * Sets the concurso ID of this asignados.
     *
     * @param concursoId the concurso ID of this asignados
     */
    public void setConcursoId(long concursoId);

    /**
     * Returns the documento of this asignados.
     *
     * @return the documento of this asignados
     */
    @AutoEscape
    public String getDocumento();

    /**
     * Sets the documento of this asignados.
     *
     * @param documento the documento of this asignados
     */
    public void setDocumento(String documento);

    /**
     * Returns the puntuacion obtenida of this asignados.
     *
     * @return the puntuacion obtenida of this asignados
     */
    @AutoEscape
    public String getPuntuacionObtenida();

    /**
     * Sets the puntuacion obtenida of this asignados.
     *
     * @param puntuacionObtenida the puntuacion obtenida of this asignados
     */
    public void setPuntuacionObtenida(String puntuacionObtenida);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.telefonica.plataformaconcursos.model.Asignados asignados);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.telefonica.plataformaconcursos.model.Asignados> toCacheModel();

    @Override
    public com.telefonica.plataformaconcursos.model.Asignados toEscapedModel();

    @Override
    public com.telefonica.plataformaconcursos.model.Asignados toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
